steps:
  test:
    image: node:20-bullseye
    commands:
      - npm install
      - npm run lint
      - npm run test
    when:
      # - event: push
      #   branch: master
      - event: manual
        evaluate: 'MANUAL_BUILD == "true"'
  build:
    image: node:20-bullseye
    commands:
      - npm install
      - npm run build
    when:
      - event: push
        branch: master
      - event: manual
        evaluate: 'MANUAL_BUILD == "true" || MANUAL_DEPLOY == "true"'
  deploy:
    image: node:20-bullseye
    environment:
      NODE_ENV: production
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - npm set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
      - npm publish
    depends_on: build
    when:
      - event: tag
        branch: master
        ref: refs/tags/v*([0-9])*(\.*([0-9]))
      - event: manual
        evaluate: 'MANUAL_DEPLOY == "true"'