import * as db from 'firebase/database';
import * as app from 'firebase/app';

export const endAt = db.endAt;
export const endBefore = db.endBefore;
export const equalTo = db.equalTo;
export const get = db.get;
export const getDatabase = db.getDatabase;
export const increment = db.increment;
export const initializeApp = app.initializeApp;
export const limitToFirst = db.limitToFirst;
export const limitToLast = db.limitToLast;
export const off = db.off;
export const onChildAdded = db.onChildAdded;
export const onChildChanged = db.onChildChanged;
export const onChildMoved = db.onChildMoved;
export const onChildRemoved = db.onChildRemoved;
export const onValue = db.onValue;
export const orderByChild = db.orderByChild;
export const orderByKey = db.orderByKey;
export const orderByPriority = db.orderByPriority;
export const orderByValue = db.orderByValue;
export const push = db.push;
export const query = db.query;
export const ref = db.ref;
export const refFromURL = db.refFromURL;
export const remove = db.remove;
export const set = db.set;
export const startAfter = db.startAfter;
export const startAt = db.startAt;
export const update = db.update;
